(function(){
	window.xjcong={
		
	},
	xjcong.api={
		getdata : function(ipurl,type,param,option,sc){
			$.ajax({
				url:ipurl,
				dataType:'JSON',
				async:true,
				type:type,
				data:param,
				timeout:10000,
				success:function(obj){
					if(sc&&sc){
						sc(obj);
					}
				}
			})
		},
		//1上传学生证首页（实名认证）
		addCertificationFirst:function(param,option,sc){
			this.getdata('/rest/certification/addCertificationFirst','POST',param,option,sc);
		},
		//2上传手持学生证照片（实名认证）
		addCertificationSecond:function(param,option,sc){
			this.getdata('/rest/certification/addCertificationSecond','POST',param,option,sc);
		},
		//3大赛报名
		signUp:function(param,option,sc){
			this.getdata('/rest/participant/signUp','GET',param,option,sc);
		},
		//4上传个人资料
		addPersonProfile:function(param,option,sc){
			this.getdata('/rest/participant/addPersonProfile','POST',param,option,sc);
		},
		//5作品投票
		vote:function(param,option,sc){
			this.getdata('/rest/ticket/vote','GET',param,option,sc);
		},
		//6单个作品的票数
		ticketTotals:function(param,option,sc){
			this.getdata('/rest/ticket/ticketTotals','GET',param,option,sc);
		},
		//7添加作品
		insertDesigns:function(param,option,sc){
			this.getdata('/rest/designs/insertDesigns','POST',param,option,sc);
		},
		//8查询我的作品
		queryDesignsDetails:function(param,option,sc){
			this.getdata('/rest/designs/queryDesignsDetails','GET',param,option,sc);
		},
		//9登录
		login:function(param,option,sc){
			this.getdata('/rest/login','POST',param,option,sc);
		},
		//10获取登录状态
		loginStatus:function(param,option,sc){
			this.getdata('/rest/loginStatus','GET',param,option,sc);
		},
		//11退出登录
		logout:function(param,option,sc){
			this.getdata('/logout','POST',param,option,sc);
		},
		//12注册发送验证码
		sendValidateCodeByCaptcha:function(param,option,sc){
			this.getdata('/rest/register/sendValidateCodeByCaptcha','POST',param,option,sc);
		},
		//13注册用户
		addUser:function(param,option,sc){
			this.getdata('/rest/register/addUser','POST',param,option,sc);
		},
		//14找回密码发送验证码
		sendValidateCode2:function(param,option,sc){
			this.getdata('/rest/findpwd/sendValidateCode','POST',param,option,sc);
		},
		//15找回密码设置密码
		updatePwd:function(param,option,sc){
			this.getdata('/rest/findpwd/updatePwd','POST',param,option,sc);
		},
		//16查询全部作品
		queryAppTicketList:function(param,option,sc){
			this.getdata('/rest/ticket/queryAppTicketList','GET',param,option,sc);
		},
		//17查询作品详情
		queryTicket:function(param,option,sc){
			this.getdata('/rest/ticket/queryTicket','GET',param,option,sc);
		},
		//18修改大赛作品请求
		updateDesigns:function(param,option,sc){
			this.getdata('/rest/designs/updateDesigns','POST',param,option,sc);
		},
		//19根据id查询别人的详情
		queryIdDesignsDetails:function(param,option,sc){
			this.getdata('/rest/designs/queryIdDesignsDetails','GET',param,option,sc);
		},
		//20点开链接就查询状态
		queryByIndex:function(param,option,sc){
			this.getdata('/rest/matchs/queryByIndex','GET',param,option,sc);
		},
//		//21添加战队头像
//		uploadCerImg:function(param,option,sc){
//			this.getdata('/rest/corps/uploadCerImg','POST',param,option,sc);
//		},
		//22添加战队
		insertCorps:function(param,option,sc){
			this.getdata('/rest/corps/insertCorps','POST',param,option,sc);
		},
		//23对添加的队员账号判断
		queryVerification:function(param,option,sc){
			this.getdata('/rest/corps/queryVerification','POST',param,option,sc);
		},
		//24修改战队
		updateCorps:function(param,option,sc){
			this.getdata('/rest/corps/updateCorps','POST',param,option,sc);
		},
		//25查询我的战队
		queryDesignsDetails:function(param,option,sc){
			this.getdata('/rest/designs/queryDesignsDetails','GET',param,option,sc);
		},
		//26查询战队详情
		queryDesignsDetails:function(param,option,sc){
			this.getdata('/rest/designs/queryDesignsDetails','GET',param,option,sc);
		},
		//27查询战队
		queryjudge:function(param,option,sc){
			this.getdata('/rest/corps/queryjudge','POST',param,option,sc);
		},
		//28审核战队
		updateCorpstoExamine:function(param,option,sc){
			this.getdata('/rest/corps/updateCorpstoExamine','POST',param,option,sc);
		},
		//28查询作品驳回原因
		queryRefuseresion:function(param,option,sc){
			this.getdata('/rest/designs/queryRefuseresion','GET',param,option,sc);
		},
		//28查询实名认证驳回原因
		lookFailReason:function(param,option,sc){
			this.getdata('/rest/certification/lookFailReason','GET',param,option,sc);
		},
		//29微信公众号自登录
		Guide:function(param,option,sc){
			this.getdata('/rest/weixin/Guide','GET',param,option,sc);
		},
		//30查询是否关注公众号和是否阅读的接口
		queryStatus:function(param,option,sc){
			this.getdata('/rest/userstatus/queryStatus','GET',param,option,sc);
		},
		//31获取图形验证码
		captcha:function(param,option,sc){
			this.getdata('/rest/captcha','POST',param,option,sc);
		},
		
		
		
		

	}
	
	
})();
